org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseSerialGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.experimental.enableScreenshotTest=true
android.compose.screenshot.maxHeapSize=4g

android.enableR8.fullMode=true

kotlin.code.style=official
ksp.incremental=true
